---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/env python3
    casepro_secret_key: "secret-key"
  roles:
    - role: onaio.postgresql
      vars:
        postgresql_version: 10
        postgresql_users:
          - name: casepro
            pass: casepro
            encrypted: true
        postgresql_databases:
          - name: casepro
            owner: casepro
            encoding: UTF-8
            hstore: true
        postgresql_database_extensions:
          - db: casepro
            extensions:
              - hstore
        postgresql_backup_enabled: false
        postgresql_enable_ssl: true
        postgresql_ssl_domain: "db.example.com"
        postgresql_ssl_ca_key: "{{ lookup('file', 'ssl/root.key') }}"
        postgresql_ssl_ca_cert: "{{ lookup('file', 'ssl/root.crt') }}"

    - role: DavidWittman.redis
      vars:
        redis_version: "2.8.24"

    - role: ansible-casepro
      vars:
        casepro_postgresql_password: casepro
